package db

// DO NOT EDIT BY HAND
//
// This code was generated by the schema.DotGo function. If you need to
// modify the database schema, please add a new schema update to update.go
// and the run 'make update-schema'.
const freshSchema = `
CREATE TABLE "artifacts" (
    id           INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    uuid         TEXT NOT NULL,
    type         TEXT NOT NULL,
    properties   TEXT NOT NULL,
    last_updated DATETIME NOT NULL,
    UNIQUE (uuid)
  );
CREATE TABLE "batches" (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name               TEXT NOT NULL,
    status             TEXT NOT NULL,
    status_message     TEXT NOT NULL,
    include_expression TEXT NOT NULL,
    constraints        TEXT NOT NULL,
    start_date         DATETIME NOT NULL,
    defaults           TEXT NOT NULL,
    config             TEXT NOT NULL,
    UNIQUE (name)
);
CREATE TABLE "instances" (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    uuid TEXT NOT NULL,
    last_update_from_source DATETIME NOT NULL,
    source_id INTEGER NOT NULL,
    overrides TEXT NOT NULL,
    properties TEXT NOT NULL,
    UNIQUE (uuid),
    FOREIGN KEY(source_id) REFERENCES sources(id)
);
CREATE TABLE instances_batches (
    instance_id              INTEGER NOT NULL,
    batch_id                 INTEGER NOT NULL,
    FOREIGN KEY(instance_id) REFERENCES instances(id) ON DELETE CASCADE,
    FOREIGN KEY(batch_id)    REFERENCES batches(id) ON DELETE CASCADE,
    UNIQUE(batch_id, instance_id)
);
CREATE TABLE "migration_windows" (
    id       INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name     TEXT NOT NULL,
    lockout  DATETIME NOT NULL,
    start    DATETIME NOT NULL,
    end      DATETIME NOT NULL,
    batch_id INTEGER NOT NULL,
    config   TEXT NOT NULL,
    UNIQUE(start, end, lockout, batch_id),
    UNIQUE(name, batch_id),
    FOREIGN KEY(batch_id) REFERENCES batches(id) ON DELETE CASCADE
);
CREATE TABLE "networks" (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    type               TEXT NOT NULL,
    uuid               TEXT NOT NULL,
    source_specific_id TEXT NOT NULL,
    location           TEXT NOT NULL,
    properties         TEXT NOT NULL,
    source_id          INTEGER NOT NULL,
    overrides          TEXT NOT NULL,
    UNIQUE (uuid),
    UNIQUE (source_specific_id, source_id),
    FOREIGN KEY(source_id) REFERENCES sources(id) ON DELETE CASCADE
  );
CREATE TABLE "queue" (
    id                               INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    instance_id                      INTEGER NOT NULL,
    batch_id                         INTEGER NOT NULL,
    migration_status                 TEXT NOT NULL,
    migration_status_message         TEXT NOT NULL,
    import_stage                     TEXT NOT NULL,
    secret_token                     TEXT NOT NULL,
    last_worker_status               INTEGER NOT NULL,
    migration_window_id              INTEGER,
    placement                        TEXT NOT NULL,
    last_background_sync             DATETIME NOT NULL,
    FOREIGN KEY(migration_window_id) REFERENCES migration_windows(id),
    FOREIGN KEY(instance_id)         REFERENCES instances(id) ON DELETE CASCADE,
    FOREIGN KEY(batch_id)            REFERENCES batches(id) ON DELETE CASCADE,
    UNIQUE (instance_id)
);
CREATE TABLE sources (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    source_type TEXT NOT NULL,
    properties TEXT NOT NULL,
    UNIQUE (name)
);
CREATE TABLE targets (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    target_type TEXT NOT NULL,
    properties TEXT NOT NULL,
    UNIQUE (name)
);
CREATE TABLE warnings (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    uuid TEXT NOT NULL,
    type TEXT NOT NULL,
    scope TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity TEXT NOT NULL,
    status TEXT NOT NULL,
    messages TEXT NOT NULL,
    count INTEGER NOT NULL,
    first_seen_date DATETIME NOT NULL,
    last_seen_date DATETIME NOT NULL,
    updated_date DATETIME NOT NULL,
    UNIQUE (uuid),
    UNIQUE (type, scope, entity_type, entity)
	);

INSERT INTO schema (version, updated_at) VALUES (20, strftime("%s"))
`
